# serverless.yml

service: covidresources

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
        cors: true 
      - http: 'ANY {proxy+}'
        cors: true 


plugins:
  - serverless-offline

